apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-ingress
  namespace: url-shortener
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts: ["short.mgbarbosa.dev"]
      secretName: url-shortener-cert-secret
  rules:
    - host: short.mgbarbosa.dev
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: url-shortener-service
                port:
                  number: 80