de:
  flapdoodle:
    mongodb:
      embedded:
        port: 27017
        version: 5.0.5
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: '6370'
    mongodb:
      uri: mongodb://localhost:65000/test
      port: 65000
      uuid-representation: standard
jwt:
  expiration-seconds: '7200'
  secret: OPDIASODASUDHASOIFAFUIPAH
  refresh-expiration-seconds: '7200'
  issuer: 'http://localhost:3000'
  audience: 'http://localhost:3000'
