name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GhCr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: m4urici0gm
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push to registry
        uses: docker/build-push-action@v3
        with:
          platforms: |
              linux/amd64
              linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: | 
            ghcr.io/m4urici0gm/url-shortener:${{ github.sha }}
            ghcr.io/m4urici0gm/url-shortener:latest
      
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://144.22.179.129:6443
          k8s-secret: ${{ secrets.KUBE_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: first-deploy
          manifests: |
            k8s/deployment.yaml
            k8s/certificate.yaml
            k8s/ingress.yaml
            k8s/service.yaml
          images: |
            ghcr.io/m4urici0gm/url-shortener:latest

          